# Generated by Django 5.1.1 on 2024-09-25 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_APP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sr_no',
            new_name='o_id',
        ),
    ]
